### ISSUE TITLE
VPN without gui

### ISSUE THREAD

**Issue by ShuP1** [firecat53/networkmanager-dmenu#48] opened 2017-10-21 15:07 UTC
With ```gui_if_available = False```,
Start a vpn shows GUI password prompt.
Thanks

**Comment by firecat53** [comment] 2017-10-22 03:26
I've tried to figure out how to set the VPN secret (password) using the gobject libraries, but so far I can't figure it out. Right now, there's two options

- edit your VPN connection profile to save the password for all users (so you won't get prompted at all)
- help me figure out a way to set the VPN secret in the code!

```
    sec = GLib.Variant.new_dict_entry(GLib.Variant.new_string('password'),  GLib.Variant.new_string('secretpassword'))
    vpn_settings.set_property(NM.SETTING_VPN_SECRETS, sec)    
    /usr/lib/python3.6/site-packages/gi/overrides/GLib.py in __len__(self)                                                                  
        404         if self.get_type_string().startswith('a') or self.get_type_string().startswith('('):                                    
        405             return self.n_children()                        
    --> 406         raise TypeError('GVariant type %s does not have a length' % self.get_type_string())                                     
        407                           
        408     def __getitem__(self, key):                             
    TypeError: GVariant type {ss} does not have a length    
```

also tried

    NM.SettingVPN.add_secret

but that didn't seem to work either. Ugh.

Documentation is [here](https://lazka.github.io/pgi-docs/index.html#NM-1.0/classes/SettingVpn.html%23NM.SettingVpn)

**Comment by CumpsD** [comment] 2019-08-01 20:23
I'd love to know to, with `nmcli` I pass in `passwd-file`, but no idea how to get it to work in python

**Comment by firecat53** [comment] 2021-03-07 01:57
Closing. Basically duplicate of #73.

**Closed by firecat53** 2021-03-07 01:57 UTC
